from unittest import result

from dotenv import load_dotenv
load_dotenv()
from langchain_mistralai import ChatMistralAI
from langchain.tools import tool

from rich import print #Rich is a Python library that allows you to create visually appealing and formatted output in the terminal. It provides various features such as colored text, tables, progress bars, and more, making it easier to display information in a clear and attractive way. In this code, we are importing the print function from the rich library to enhance the output of our program with colors and formatting options.

#1 Creating a tool

@tool
def get_text_length(text: str) -> int: #input in string, output in integer
    """Calculate the length of the given text.""" #This is a docstring that informs the usecase of the tool to the LLM. It provides a brief description of what the function does, which is to calculate the length of the given text. The docstring is used to explain the purpose and functionality of the function, making it easier for users to understand how to use it effectively.
    return len(text)

#2 Using LLM

llm = ChatMistralAI(model="mistral-small-2506")

#3 TOOL BINDING

#Tool binding is the process of connecting a tool (in this case, the get_text_length function) to a language model (LLM) so that the model can utilize the tool's functionality when generating responses. This allows the LLM to perform specific tasks, such as calculating the length of a given text, by invoking the tool directly within its response generation process. By binding the tool to the LLM, we enable the model to access and use the tool's capabilities seamlessly as part of its interactions with users.
#Here we provide all the tools we have, but in this case we cuurently have only one toool which is get_text_length. The llm.bind_tools method is used to bind the tool to the language model, allowing it to utilize the tool's functionality when generating responses.
llm_with_tool=llm.bind_tools([get_text_length])

result1=llm.invoke("Return the number of characters in given test: Hello How are you!") #Here we use normal LLM where I did not bind any tool

result2=llm_with_tool.invoke("Return the number of characters in given test: Hello How are you!") #Here we are using the llm with tool binding, which means that the model can now utilize the get_text_length tool to calculate the length of the input text "hello". When we invoke the llm_with_tool with the input "hello", it will recognize that it has access to the get_text_length tool and will use it to compute the length of the text, which is 5 in this case. The result will be the output generated by the model, which may include the calculated length of the input text along with any additional response generated by the model based on its understanding of the input.

print(result1)#In output the total_tokens will be less than the because here we are not using any tool, so the model is generating a response based solely on its internal knowledge and understanding of the input text "hello". The total_tokens count includes both the input tokens and the output tokens, so when we do not use any tools, the response generated by the model may be shorter and more concise, resulting in a lower total token count compared to when we use a tool that adds additional information or functionality to the response.
print()
print()
print(result2) #In output the total_tokens will be more than the previous one because now it is using the tool to calculate the length of the text, which adds additional tokens to the response generated by the model. The total_tokens count includes both the input tokens and the output tokens, so when we use the tool, it contributes to an increase in the total token count in the response.

#TOOL CALLING

#To do tool calling we dont't have to write specific code becaause when we bind the tool to the LLM, the model automatically recognizes that it has access to the tool and can call it whenever it determines that the tool's functionality is relevant to the user's query. In this case, when we invoke the llm_with_tool with the input "hello", the model will analyze the input and determine that it can use the get_text_length tool to calculate the length of the text. The model will then call the tool internally as part of its response generation process, allowing it to provide a more accurate and informative response based on the functionality of the tool. Therefore, we don't need to write specific code for tool calling, as it is handled automatically by the model once the tool is bound to it.




